library(mgcv)
data1=read.table("F:\\4. me\\kelautan\\HAHAHIHI\\GAM\\GAM.txt", header=T)
data1
attach(data1)
names(data1)
model1<-gam(FISHING~(s(SST)+s(CHL)+s(SSH)+s(ARUS)), family=gaussian, data=data1)
summary(model1)
AIC(model1)
BIC(model1)
plot(model1)
model2<-gam(FISHING~s(SST), family=gaussian, data=data1)
summary(model2)
AIC(model2)
BIC(model2)
plot(model2)
model3<-gam(FISHING~s(CHL), family=gaussian, data=data1)
summary(model3)
AIC(model3)
BIC(model3)
plot(model3)
model4<-gam(FISHING~s(SSH), family=gaussian, data=data1)
summary(model4)
AIC(model4)
BIC(model4)
plot(model4)
model5<-gam(FISHING~s(ARUS), family=gaussian, data=data1)
summary(model5)
AIC(model5)
BIC(model5)
plot(model5)
model6<-gam(FISHING~s(CHL)+s(SST), family=gaussian, data=data1)
summary(model6)
AIC(model6)
BIC(model6)
plot(model6)
model7<-gam(FISHING~s(CHL)+s(ARUS), family=gaussian, data=data1)
summary(model7)
AIC(model7)
BIC(model7)
plot(model7)
model8<-gam(FISHING~s(CHL)+s(SSH), family=gaussian, data=data1)
summary(model8)
AIC(model8)
BIC(model8)
plot(model8)
model9<-gam(FISHING~s(SST)+s(ARUS), family=gaussian, data=data1)
summary(model9)
AIC(model9)
BIC(model9)
plot(model9)
model10<-gam(FISHING~s(SST)+s(SSH), family=gaussian, data=data1)
summary(model10)
AIC(model10)
BIC(model10)
plot(model10)
model11<-gam(FISHING~s(ARUS)+s(SSH), family=gaussian, data=data1)
summary(model11)
AIC(model11)
BIC(model11)
plot(model11)
model12<-gam(FISHING~s(SST)+s(CHL)+s(SSH), family=gaussian, data=data1)
summary(model12)
AIC(model12)
BIC(model12)
plot(model12)
model13<-gam(FISHING~s(SST)+s(CHL)+s(ARUS), family=gaussian, data=data1)
summary(model13)
AIC(model13)
BIC(model13)
plot(model13)
model14<-gam(FISHING~s(SST)+s(ARUS)+s(SSH), family=gaussian, data=data1)
summary(model14)
AIC(model14)
BIC(model14)
plot(model14)
model15<-gam(FISHING~s(ARUS)+s(CHL)+s(SSH), family=gaussian, data=data1)
summary(model15)
AIC(model15)
BIC(model15)
plot(model15)



plot (model1,xlab="CURRENT",ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model2,xlab="SST",ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model3,xlab="CHL-A", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model4,xlab="SSH", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model5,xlab="CURRENT", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model6,xlab="SST", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model7,xlab="CHL-A", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model8,xlab="SSH", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model9,xlab="CURRENT", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model10,xlab="SSH", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model11,xlab="SSH", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model12,xlab="SST", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model13,xlab="CURRENT", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model14,xlab="SSH", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
plot (model15,xlab="SSH", ylab="FISH", font.lab=46, cex.lab=1, shade=TRUE)
